//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int id { get; set; }
        public Nullable<int> horaInicio { get; set; }
        public Nullable<int> horaFin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> capacidad { get; set; }
        public int idServicio { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
