//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Clase = new HashSet<Clase>();
        }
    
        public int cedula { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string nombre { get; set; }
        public string distrito { get; set; }
        public string canton { get; set; }
        public string provincia { get; set; }
        public Nullable<int> salario { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> idPuesto { get; set; }
        public Nullable<int> idPlanilla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase> Clase { get; set; }
        public virtual Planilla Planilla { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
