//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int nSerie { get; set; }
        public string marca { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public Nullable<int> idTipoEquipo { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> costo { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoEquipo TipoEquipo { get; set; }
    }
}
