//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gymtecdatabaseEntities1 : DbContext
    {
        public gymtecdatabaseEntities1()
            : base("name=gymtecdatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
        public virtual DbSet<TipoEquipo> TipoEquipo { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<mostrar_clases> mostrar_clases { get; set; }
        public virtual DbSet<mostrar_clientes> mostrar_clientes { get; set; }
        public virtual DbSet<mostrar_inventario> mostrar_inventario { get; set; }
        public virtual DbSet<tratamientos_asociados> tratamientos_asociados { get; set; }
    
        public virtual int copiar_calendario(Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechanuevo)
        {
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("fechainicio", fechainicio) :
                new ObjectParameter("fechainicio", typeof(System.DateTime));
    
            var fechanuevoParameter = fechanuevo.HasValue ?
                new ObjectParameter("fechanuevo", fechanuevo) :
                new ObjectParameter("fechanuevo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("copiar_calendario", fechainicioParameter, fechanuevoParameter);
        }
    
        public virtual int copiar_gimnasio(Nullable<int> idsucursal, string imagen, string nombre, string distrito, string canton, string provincia)
        {
            var idsucursalParameter = idsucursal.HasValue ?
                new ObjectParameter("idsucursal", idsucursal) :
                new ObjectParameter("idsucursal", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(string));
    
            var cantonParameter = canton != null ?
                new ObjectParameter("canton", canton) :
                new ObjectParameter("canton", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("copiar_gimnasio", idsucursalParameter, imagenParameter, nombreParameter, distritoParameter, cantonParameter, provinciaParameter);
        }
    
        public virtual ObjectResult<filtro_clase_cliente_Result> filtro_clase_cliente(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filtro_clase_cliente_Result>("filtro_clase_cliente", id_clienteParameter);
        }
    
        public virtual ObjectResult<filtro_clases_Result> filtro_clases(Nullable<int> id_sucursal, string nombre_servicio, Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechafin)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            var nombre_servicioParameter = nombre_servicio != null ?
                new ObjectParameter("nombre_servicio", nombre_servicio) :
                new ObjectParameter("nombre_servicio", typeof(string));
    
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("fechainicio", fechainicio) :
                new ObjectParameter("fechainicio", typeof(System.DateTime));
    
            var fechafinParameter = fechafin.HasValue ?
                new ObjectParameter("fechafin", fechafin) :
                new ObjectParameter("fechafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filtro_clases_Result>("filtro_clases", id_sucursalParameter, nombre_servicioParameter, fechainicioParameter, fechafinParameter);
        }
    
        public virtual ObjectResult<generar_planilla_Result> generar_planilla(Nullable<int> idsucursal)
        {
            var idsucursalParameter = idsucursal.HasValue ?
                new ObjectParameter("idsucursal", idsucursal) :
                new ObjectParameter("idsucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<generar_planilla_Result>("generar_planilla", idsucursalParameter);
        }
    
        public virtual ObjectResult<inventario_gimnasio_Result> inventario_gimnasio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<inventario_gimnasio_Result>("inventario_gimnasio", id_sucursalParameter);
        }
    
        public virtual ObjectResult<login_admin_Result> login_admin(string email, string contrasena)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_admin_Result>("login_admin", emailParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<mostrar_clases_gimnacio_Result> mostrar_clases_gimnacio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mostrar_clases_gimnacio_Result>("mostrar_clases_gimnacio", id_sucursalParameter);
        }
    
        public virtual ObjectResult<mostrar_clases_gimnasio_Result> mostrar_clases_gimnasio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mostrar_clases_gimnasio_Result>("mostrar_clases_gimnasio", id_sucursalParameter);
        }
    
        public virtual ObjectResult<productos_gimnasio_Result> productos_gimnasio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productos_gimnasio_Result>("productos_gimnasio", id_sucursalParameter);
        }
    
        public virtual ObjectResult<servicios_gimnasio_Result> servicios_gimnasio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<servicios_gimnasio_Result>("servicios_gimnasio", id_sucursalParameter);
        }
    
        public virtual ObjectResult<tratamientos_gimnasio_Result> tratamientos_gimnasio(Nullable<int> id_sucursal)
        {
            var id_sucursalParameter = id_sucursal.HasValue ?
                new ObjectParameter("id_sucursal", id_sucursal) :
                new ObjectParameter("id_sucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tratamientos_gimnasio_Result>("tratamientos_gimnasio", id_sucursalParameter);
        }
    }
}
