//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mostrar_inventario
    {
        public int nserie { get; set; }
        public string marca { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public Nullable<int> idsucursal { get; set; }
        public string tipoEquipo { get; set; }
        public Nullable<int> costo { get; set; }
        public string nombreSucursal { get; set; }
    }
}
