//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mostrar_empleados
    {
        public int cedula { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string nombre { get; set; }
        public string distrito { get; set; }
        public string canton { get; set; }
        public string provincia { get; set; }
        public Nullable<int> salario { get; set; }
        public string puesto { get; set; }
        public string tipoPlanilla { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string nombreSucursal { get; set; }
    }
}
