//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mostrar_clases
    {
        public int id { get; set; }
        public Nullable<int> horaInicio { get; set; }
        public Nullable<int> horaFin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string nombreServicio { get; set; }
        public string nombreInstructor { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string nombreSucursal { get; set; }
    }
}
