//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymtec_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mostrar_empleados
    {
        public int cedula { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string nombre { get; set; }
        public string distrito { get; set; }
        public string canton { get; set; }
        public string provincia { get; set; }
        public Nullable<int> salario { get; set; }
        public string puesto { get; set; }
        public string tipoPlanilla { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string nombreSucursal { get; set; }
        public Nullable<int> idPuesto { get; set; }
        public Nullable<int> idPlanilla { get; set; }
    }
}
